source $HOME/AppData/Local/nvim/vim-plug/plugins.vim
source $HOME/AppData/Local/nvim/general/settings.vim
source $HOME/AppData/Local/nvim/general/paths.vim
source $HOME/AppData/Local/nvim/keys/mappings.vim
source $HOME/AppData/Local/nvim/themes/halcyon.vim
source $HOME/AppData/Local/nvim/themes/airline.vim
source $HOME/AppData/Local/nvim/plug-config/chadtree.vim
source $HOME/AppData/Local/nvim/plug-config/coc/coc.vim
source $HOME/AppData/Local/nvim/plug-config/ale.vim
source $HOME/AppData/Local/nvim/plug-config/startscreen.vim
